# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0438\u043c\u044f')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('phone', models.CharField(max_length=255, verbose_name='\u0442\u0435\u043b\u0435\u0444\u043e\u043d\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0441\u043e\u0437\u0434\u0430\u043d\u043e')),
            ],
            options={
                'verbose_name': '\u0437\u0430\u043f\u0440\u043e\u0441',
                'verbose_name_plural': '\u0437\u0430\u043f\u0440\u043e\u0441\u044b',
            },
        ),
    ]
